server:
  port: 8080
endpoints:
  categories: /categories
  security: http://localhost:8090/auth/validToken
spring:
  resources:
    add-mappings: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: interviews