server:
  port: 8080
endpoints:
  categories: /categories
  
security:
  endpoint: http://localhost:8090/auth/validToken
  tokenHeader: Authorization
  
spring:
  resources:
    add-mappings: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: interviews