server:
  port: 8090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: interviews
      
security:
  testTokenSecret: ShaquilleONeal
  expirationTime: 2100000
  tokenHeader: Authorization