server:
  port: 8080

spring:
  data:
    mongodb:
      host: 172.17.0.3
      port: 27017
      database: interviews
  
security:
  endpoint: http://security-service:8080/auth/validToken
  tokenHeader: Authorization